#pragma once
// Generated by 'hashgen'.

// clang-format off
enum {
  ScriptHash_empty = 1493338014, // ''
  ScriptHash_any = 119688326, // 'any'
  ScriptHash_bool = 863051777, // 'bool'
  ScriptHash_break = 1725904472, // 'break'
  ScriptHash_continue = 1788505286, // 'continue'
  ScriptHash_else = 1760833515, // 'else'
  ScriptHash_for = 327857603, // 'for'
  ScriptHash_id = 99847454, // 'id'
  ScriptHash_if = 3180054279, // 'if'
  ScriptHash_null = 960167585, // 'null'
  ScriptHash_num = 537714186, // 'num'
  ScriptHash_range = 2171983458, // 'range'
  ScriptHash_return = 3227182607, // 'return'
  ScriptHash_str = 2717725020, // 'str'
  ScriptHash_to = 853473721, // 'to'
  ScriptHash_var = 172593793, // 'var'
  ScriptHash_while = 1492262353, // 'while'
};
// clang-format on
