#pragma once
// Generated by 'hashgen'.

// clang-format off
enum {
  DevHash_Dev = 2547616407, // 'Dev'
  DevHash_Debug = 1184290027, // 'Debug'
  DevHash_DevPanelClose = 3611106621, // 'DevPanelClose'
  DevHash_DevPanelEcs = 2791786667, // 'DevPanelEcs'
  DevHash_DevPanelRenderer = 2341646233, // 'DevPanelRenderer'
  DevHash_DevPanelSound = 4051400737, // 'DevPanelSound'
  DevHash_DevPanelTime = 1086967750, // 'DevPanelTime'
  DevHash_DevPanelTrace = 1438144397, // 'DevPanelTrace'
  DevHash_DevTimePauseToggle = 2088614054, // 'DevTimePauseToggle'
  DevHash_DevTimeScaleDown = 4137843889, // 'DevTimeScaleDown'
  DevHash_DevTimeScaleUp = 3973438992, // 'DevTimeScaleUp'
  DevHash_DevTimeStep = 3334101101, // 'DevTimeStep'
};
// clang-format on
